### ISSUE TITLE
RDF export

### ISSUE THREAD

**Issue by Bench2023** [Hoogkamer/webboardapp#13]
not an issue but a request. Would it be possible to create an rdf export capability as this will make the editing of knowledge graphs really powerful. If there is a simple way to do this from the existing putput options please let me know.

**Comment by Bench2023** [comment]
Thanks @Hoogkamer I'll have a look at ontotext refine. I am really impressed with Termboard BTW. Resource Description Framework (a W3C open standard) just allows a structured way of describing "subject" "predicate" and "object" (which your Termboard system calls (Source Term, Relation name, Target name) and would allow the output to be imported to other knowledge graph tools for editing. I'll let you know how I get on

**Comment by vinayxbox** [comment]
Very impressive work @Hoogkamer. Atleast you can allow export in Json-LD format https://json-ld.org/ so that we can use free to us RDF creator's to generate RDF. Output also will be easier to read.

**Comment by Bench2023** [comment]
![image](https://user-images.githubusercontent.com/131291639/235225581-339497c5-2e64-401d-a474-ae30d90c5afa.png)
I think that can be modelled in this way where age is an attribute of an agent. Although I confess to not fully understanding the meaning of Group member and agent here but hopefully the example JSON-LD helps anyway.

I bleive the JSON-LD (although I am no expert) would be written like this: 

[example.txt](https://github.com/Hoogkamer/webboardapp/files/11356379/example.txt)
