### ISSUE TITLE
Recursive relationship

### ISSUE THREAD

**Issue by sfrauenfelder** [Hoogkamer/webboardapp#2]
Sometimes I need to model a recursive relationship. Could that be added?
E.g. sets can contain subsets, which can contain subsets. 
Or a balance sheet has items, which aggregate lower level items, which in turn ...
Would be much appreciated!

**Comment by Hoogkamer** [comment]
Yes, you can use groups for that: https://www.youtube.com/watch?v=CymmpNvgk80
and you can also collapse/expand these: https://www.youtube.com/watch?v=K_gW93-lwbE
Does that help?

**Comment by sfrauenfelder** [comment]
I mean I need to display a relationship arrow, that starts and ends at the same term. With that, it defines a tree-like structure, with an unlimited number of branches and levels. Like this:
![afbeelding](https://user-images.githubusercontent.com/42144635/155710283-4365d059-2bfc-45b6-a140-2ff13cfdf635.png)

Grouping just gives one level at a time, and of course I can't draw an unlimited number of groups (don't have time for that;-) ).

**Comment by Hoogkamer** [comment]
Ah, yes that will save a lot of time in your usecase :) You can simply drag the relation to itself, here an example with 3 self-relations
![image](https://user-images.githubusercontent.com/17671871/155715510-1fc0ec8d-06d7-4f28-914f-37ec8b344636.png)

**Comment by sfrauenfelder** [comment]
I have missed that completely! Thanks.
One remark: could the first one (labelled "1") be a bit wider? And not run behind the term?

**Comment by Hoogkamer** [comment]
![image](https://user-images.githubusercontent.com/17671871/155839531-6e810b24-9288-461d-89ee-d66b4802ba2d.png)
It is now done as in above picture

**Comment by sfrauenfelder** [comment]
Thanks, like it!
Follow up question... is it feasible to make the relationship "positionable", so that I can place in another position with respect to the term? So that I could for example move it to top-right, to-left. or even *any* position? Then I could prevent overlap with other relations.

**Comment by Hoogkamer** [comment]
Could be, but sometimes less is more :). You have 4 options now, and is selectable in the context menu of the relation:   ![image](https://user-images.githubusercontent.com/17671871/156054215-df275faf-011d-457f-af37-d2adec7333ce.png) 
![image](https://user-images.githubusercontent.com/17671871/156054294-34320846-1582-4a33-a91f-e43b7f7aded7.png)

**Comment by sfrauenfelder** [comment]
Great, thanks!
