### ISSUE TITLE
Definitions ("descriptions") for terms

### ISSUE THREAD

**Issue by sfrauenfelder** [Hoogkamer/webboardapp#3]
I would like to be able to define or describe each term, and store that in Termboard too.
Maybe it can be shown when hovering over the term. Or have an option to display all definitions to the right of each term.
I would also like to be able to define/describe relationships, and add cardinality/optionality.

**Comment by Hoogkamer** [comment]
Yes you can store a lot of extra information and (dropdown) fields and hyperlinks for each term/group/relation. For that you can use the sidebar, see "movie 3"  on the homepage. I do not yet have a movie for the dropdown fields, but maybe it will explain itself.... You can add the fields if you are in the document view in the sidebar (have nothing selected on the canvas)

**Comment by sfrauenfelder** [comment]
Missed that too, sorry.
But could the text also appear in/over the diagram, when hovering over a term?

**Comment by sfrauenfelder** [comment]
Okay, let's leave this as is.
Thanks for all your quick replies.
I'll be looking at the videos, before starting any more issues.
